name: Bug report
description: Create a report to help improve SmartifyOS
labels: ["bug"]
body:
    - type: textarea
      id: description
      attributes:
          label: Describe the bug
          placeholder: "A clear and concise description of what the bug is."
      validations:
          required: true
    - type: textarea
      id: steps
      attributes:
          label: Steps To Reproduce
          placeholder: |
              1. Go to '...'
              2. Click on '....'
              3. Scroll down to '....'
              4. See error
      validations:
          required: true
    - type: textarea
      id: expected
      attributes:
          label: Expected behavior
          placeholder: A clear and concise description of what you expected to happen.
      validations:
          required: true
    - type: textarea
      id: additional
      attributes:
          label: Additional context
          placeholder: Add any other context or screenshots about the problem here.
